### ISSUE TITLE
API用法

### ISSUE THREAD

**Issue by GodtzzZ1** [xusenlin/VueElementUiAdmin#10]
您好，我用的您的模板有点问题不知道怎么解决，想问一下
1. api绑定和之前的版本方法一样吗？
2. 访问后端的端口路径在哪里配置？
希望您能帮我解答一下，谢谢！

**Comment by xusenlin** [comment]
> 您好，我用的您的模板有点问题不知道怎么解决，想问一下
> 
> 1. api绑定和之前的版本方法一样吗？
> 2. 访问后端的端口路径在哪里配置？
>    希望您能帮我解答一下，谢谢！

你好，目前在使用最新的依赖重构了项目，让目录和结构更清晰，里面也会有请求和各种字段验证的实例。

**Comment by xusenlin** [comment]
> 您好，我用的您的模板有点问题不知道怎么解决，想问一下
> 
> 1. api绑定和之前的版本方法一样吗？
> 2. 访问后端的端口路径在哪里配置？
>    希望您能帮我解答一下，谢谢！

你已经可以使用最新版去开发了，所有的配置都在config里哈，可以查看里面的示例。

**Comment by GodtzzZ1** [comment]
好的，非常感谢！
