### ISSUE TITLE
您好，您能否说一下实现菜单权限控制的流程（在Menu/index下实现）

### ISSUE THREAD

**Issue by roobtyan** [xusenlin/VueElementUiAdmin#6]
这部分确实不太会做，希望能够得到您的答复！

**Comment by xusenlin** [comment]
> 这部分确实不太会做，希望能够得到您的答复！

您好，这个得根据后端设计得权限系统来考虑。一般来说，我们系统会有很多角色，不同的角色拥有不同的权限key(关键字)，一个用户可能会拥有多个角色，角色其实是把很多权限打包之后给定一个名称（如，普通管理员）。对于前端来说，“普通管理员”是给用户看的，我们不用去关心角色，只关心登陆的用户拥有的多个角色的权限集合key。因此，在用户登陆的时候应该拿到当前用户所有的权限（一个数组）如 
```
[home,deleteUser,addUser,...]
```
我们把他存在本地。

在utils文件夹里有v-permissions.js和dataStorage.js有一个hasPermissions函数都是用来判断权限的。

比如你说的在Menu/index下实现。我们先在同目录的menu.js里每个菜单添加一个属性PermissionsKey。像
```
articleManage.articleList = {
  name: '文章列表',
  PermissionsKey:'viewArticle',
  path: '/article/article_list',
};
```

添加好这些key之后，在Menu/index循环导入的菜单，配合hasPermissions函数来决定是否添加到导出的菜单里面。在页面上我们可以通过注册v-permissions指令去控制。
当然，这些可能因为后端权限的设计有所不同。不过思路都是一样的，权限key的约定是不可避免的，
这其中也可以配合动态添加路由来做。

**Comment by roobtyan** [comment]
非常感谢您的回复，我大致明白怎么做了，谢谢您！

**Comment by Hanson** [comment]
刚好楼主问了我想问的问题，我也看懂了作者的思路了，这里另外问一个相似的

> 这其中也可以配合动态添加路由来做

这个动态路由应该如何做呢？如果只是单纯控制菜单的话，有 path 也是可以进行访问的

**Comment by xusenlin** [comment]
> 刚好楼主问了我想问的问题，我也看懂了作者的思路了，这里另外问一个相似的
> 
> > 这其中也可以配合动态添加路由来做
> 
> 这个动态路由应该如何做呢？如果只是单纯控制菜单的话，有 path 也是可以进行访问的


嗯嗯，将所有的路由定义好，但是只有登录页面和首页（必要的话）以及404页面 真正的添加到系统里，登陆成功之后根据权限Key动态（router.addRoutes）将需要的路由追加到系统里。具体可以查看官方api。


```
export const constantRouterMap = [
  { path: '/login', component: () => import('@/views/login/index'), hidden: true },
  { path: '/404', component: () => import('@/views/404'), hidden: true },
  {
    path: '/',
    component: Layout,
    redirect: '/dashboard',
    name: 'Dashboard',
    children: [
        {
        path: 'dashboard',
        meta: { title: '首页', icon: 'dashboard', noCache: true },
        component: () => import('@/views/dashboard/index')
      }
    ],
  },
  //{ path: '*', redirect: '/404', hidden: true }
]

//这部分路由是后面根据权限添加需要的路由到系统里
export const asyncRouterMap = [
  InstitutionsManage,
  StudentManage,
  TrainingClass,
  TestManage,
  ResourceManage,
  NotificationManage,
  Settings,
  HelpCenter
]

export default new Router({
  // mode: 'history', //后端支持可开
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap
})
```
