### ISSUE TITLE
build打包文件过大

### ISSUE THREAD

**Issue by DeYuanGeGe** [xusenlin/VueElementUiAdmin#8]
打包方式有3：
1：npm run build
2：npm run build:dev
3：npm run build:test
问题--------------------
如果使用npm run build生成的包没有app.js且js部分全在js目录下
然而使用2,3打出来的包没有js目录，且有一个app.js包，这个包特别大，有9M多
很难想象现在加载这个页面要多长时间，看看大神是否有办法解决这个问题

**Comment by xusenlin** [comment]
> 打包方式有3：
> 1：npm run build
> 2：npm run build:dev
> 3：npm run build:test
> 问题--------------------
> 如果使用npm run build生成的包没有app.js且js部分全在js目录下
> 然而使用2,3打出来的包没有js目录，且有一个app.js包，这个包特别大，有9M多
> 很难想象现在加载这个页面要多长时间，看看大神是否有办法解决这个问题

您好，感谢你反馈此问题，已经修复。你可以根据自己情况添加更多打包方式。
